### PR TITLE
add ability to turn off low voltage from command line

### PR DESCRIPTION
**Pull request by jstupak**
We want this at FNAL for FPIX module testing.  Some other commands would be useful as well, but I thought Id propose just this one for now in case it violates some design philosophy.

### CODE REVIEW

**Comment by ursl** [comment]
Hi,

why do you need this? If you do something like this, then you need a lot
more as well, I think.

**Comment by simonspa** [comment]
Hi @jstupak,

not sure what the scope of the tests is that you perform here, but have you checked the Python command line which is provided? It gives you access to all the API-level functions such as `Pon`, `Poff` etc.

/Simon

**Comment by drberry85** [comment]
Urs and Simon,

John just wants to run the IV testing with the low voltage turned off. @simonspa could you give an example of how to use the Python command line with elComandante? We have limited experience with it here at FNAL.

Doug

**Comment by ursl** [comment]
Hi Doug,

apologies for repeating myself: Why do you want to run the IV test
with low voltage turned off? (Mainly just curious).

Cheers,
--U.

**Comment by jstupak** [comment]
Hello everyone,

@Urs We want to avoid the added heat produced by the low voltage.

@Simon We run pXar through elComandante without a gui.  It seems to me like the Cmd test can’t be run without the gui.  This is what you meant by python command line, right?

Regards,
John

##########################
John Stupak III

Postdoctoral Research Associate
Purdue University Calumet
jstupak@fnal.gov<mailto:jstupak@fnal.gov>
508-254-5387
skype: JohnStupak
gChat: JohnStupak
##########################

On Sep 29, 2015, at 8:06 AM, Urs Langenegger <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Doug,

apologies for repeating myself: Why do you want to run the IV test
with low voltage turned off? (Mainly just curious).

Cheers,
--U.

**Comment by ursl** [comment]
Hi John,

can you please try the master HEAD and use

IV:powerOff

I'd rather not add the parsing to pXar.cc. If the above works for your
usecase, then I'll add the call to PixTest::runCommand to the other
tests as well and provide for some state passing.

Many thanks.

Cheers,
--U.

**Comment by jstupak** [comment]
I think there is an issue with both of our solutions.  Is there a way to pipe in a command to pxar without having pxar exit afterwards?  I tested my solution by launching pxar then typing poff, and it did exactly what I want.  But for elComandante we cat a file which contains the commands we want to run and pipe this to pxar.  But when I try this with my solution or yours, pxar just closes immediately after launching.

**Comment by ursl** [comment]
Hi John,

I don't understand (and I was confused on my own). If I pipe a file (see below) into pXar, I see

marwees>cat ../main/itest | ../bin/pXar -d testROC -v DEBUG

// snip //

[07:24:48.055]     INFO: enter 'restricted' command line mode
[07:24:48.055]     INFO: enter test to run
pxar> subtest: ->poweroff<- input: ->IV<-
[07:24:48.056]     INFO:   test: IV no parameter change
[07:24:48.056]     INFO:   running: iv
[07:24:48.059]    DEBUG: <PixTestIV.cc/runCommand:L103> running command: poweroff
[07:24:48.059]    DEBUG: <PixTest.cc/powerOff:L732> PixTest::hvOff() api::Poff()
[07:24:48.060]    DEBUG: <PixTestIV.cc/~PixTestIV:L96> PixTestIV dtor
[07:24:48.060]     INFO: enter test to run
pxar> parameters: ->5<- input: ->delay<-
[07:24:48.060]     INFO:   test: delay setting parameters: ->5<-
[07:24:48.060]     INFO: delay test by 5 seconds...
[07:24:53.062]     INFO: enter test to run
pxar> [07:24:53.062]     INFO:   test: IV no parameter change
[07:24:53.062]     INFO:   running: iv
[07:24:53.062]    ERROR: <PixTestIV.cc/doTest:L111> Not built with HV supply support.
[07:24:53.062]    DEBUG: <PixTestIV.cc/~PixTestIV:L96> PixTestIV dtor
[07:24:53.062]     INFO: enter test to run
pxar> [07:24:53.062]     INFO:   test: q no parameter change
[07:24:53.062]    DEBUG: <PixMonitor.cc/dumpSummaries:L39> PixMonitor::dumpSummaries
[07:24:53.063]    QUIET: Connection to board 66 closed.
[07:24:53.685]     INFO: pXar: this is the end, my friend
[07:24:53.685]    DEBUG: <PixSetup.cc/~PixSetup:L68> PixSetup free fPxarMemory


marwees>cat ../main/itest
IV:poweroff
delay 5
IV
q

I would think that is what is desired: IV is instantiated and used to turn of LV, and then destroyed. IV is (again) instantiated and "doTest" is done, and then destroyed.  The delay is only there for me to check visually that the LED goes off. And then the pipe is terminated by q (this is also achieved by EOF). If you close the pipe, pXar is shutting down, and I think that is a feature. As long as you do not close the pipe it will not shut down. The proof (I think) is the following short perl program that opens a pipe into pXar and waits for your input (the same can of course be achieved directly, but then it's not a pipe): 


    #! /usr/bin/perl

    use FileHandle; 
    use IPC::Open2;
    $pid = open2(*Reader, *Writer, "../bin/pXar -v DEBUG -d testROC");

    while(<>) {
        chop($_);
        print "TO PXAR: $_\n";
        print Writer "$_\n";
        if ($_ eq "q") {last;}
    }


The commit that I pushed minutes ago (by now more than a few minutes...) is in fact not necessary. Just calling a test will invoke its doTest method.

Maybe you can explain better what your problem is. 

Cheers,
--U.

**Comment by urs** [comment]
Hi guys,

can you please remove me from this mailing list? I am not the Urs you are
looking for...

http://steve-lovelace.com/wordpress/wp-content/uploads/2012/10/not-the-droids-youre-looking-for.png

best
Urs

Urs Langenegger <notifications@github.com> schrieb am Mi., 30. Sep. 2015 um
08:02 Uhr:

**Comment by ursl** [comment]
Hi,

my guess would be that you got into this because of an @ Urs instead
of @ursl in John's post from yesterday. I edited that post, but apart
from that I have no idea how to change that. Filter the thread if my
edit does not cure the problem or make another proposal. Maybe
https://developer.github.com/v3/activity/notifications/#set-a-thread-subscription
could help, but I think you'd have to do that.

Cheers,
--U.

**Comment by urs** [comment]
No worries :)

Thanks for your help!

Greetings from Berlin!
Urs

Urs Langenegger <notifications@github.com> schrieb am Mi., 30. Sep. 2015 um
08:25 Uhr:

**Comment by jstupak** [comment]
Sorry Urs.  If you view the thread on the web, there is an unsubscribe button.

To the other Urs, elComandante does not use pXar to do the IV scan.  elComandante simply launches pXar (connected to a specific DTB) without a gui and does not tell it to do anything, so that the HV is enabled, then sends a sweep command to the keithley which does the scan itself.  So the file I would cat and pipe would simply contain "IV:poweroff".  The problem is, that we then need this instance of pXar to persist for some unspecified/unpredictable period of time.

I can't test it now, but I think some arbitrarily long delay might work.  I suspect when the IV scan finishes that elComandante may terminate the process running pXar, which might do the trick.

**Comment by simonspa** [comment]
@drberry85 it's just an interactive CL, so probably not what you were looking for. This was not clear to me from the first request you made. The above solution is probably better suited.

**Comment by ursl** [comment]
added this

**Pull request closed without merging**
