### PR TITLE
Some updates to the decoder modules

### PR DESCRIPTION
**Pull request by simonspa**
This PR includes changes to the pxarCore decoder modules and some other changes:

* Fix interesting chip feature in software that produces noise bursts when first enabling the pixels and then attach the column periphery
* Extend `pxar::Event` class to allow easy access to all TBM header and trailer parameters
* Fix some minor bugs in printout (IFLOG) and initialization of members (statistics)
* Factorize dtbDataSource from the rest of the decoder to be more flexible
* Introduce new data source form already recorded raw data - this allows to use the pxarCore decoder modules also when not getting fresh data from a DTB
* allow to set the TBM token chain length for every TBM core separately

Some more rework went into the Dummy DTB
* Dummy DTB now a low-level emulator of the DTB
* Replaces the RPC CTestboard class instead of the HAL
* This allows to also test the HAL and decoder classes with pseudo data, not only the API level functions
* New "generator" is able to produce pseudo detector data from chips or modules.

### CODE REVIEW

**Comment by simonspa** [comment]
There is actually a discussion still pending that needs to be resolved before this can be merged, see #276 (concerning the TBM token chains and the handling of missing ROCs)

**Comment by simonspa** [comment]
This now includes fixes for the "modules with bypassed ROCs" by @aehart as well as the RPC level emulator for the DTB.

I think this is ready for a merge.

This PR updates the required firmware to FW4.2. Beat implemented some bugfixes compared to FW4.0, but all of them consider the handling of triggers and the TBM emulator.

**Comment by ursl** [comment]
I did not manage to run the s-curves successfully with this version. Trimming did finish reasonably, though.

**Comment by simonspa** [comment]
Hi Urs,

What was the problem with the s-curves? Just the regular readout problem we are still experiencing or something different?

Cheers,
Simon

Am 11. Juni 2015 11:29:39 MESZ, schrieb Urs Langenegger <notifications@github.com>:

**Comment by ursl** [comment]
Hi Simon,

yes, "just" the r/o problems. I had tried with Wolfram's default
parameters. But I failed to see an improvement. (I have experienced one
case where Wolfram's parameters cured the r/o problems, but have not
reproduced that experience so far).

Cheers,
--U.

**Pull request merged**
