### PR TITLE
Add delay before/between executing test

### PR DESCRIPTION
**Pull request by piberger**
This adds a way to add a delay before/between executing tests with a "delay n_seconds", eg. "delay 60" command. Useful for letting the temperature stabilize after power on of the modules.

### CODE REVIEW

**Comment by simonspa** [comment]
Please do not use usleep since this will not compile on windows, also the header you include doesn't exist there.

There is a function `pxar::mDelay(uint32_t millosec)` to be used in such cases. It lives in core/utils/helpers.h

**Comment by piberger** [comment]
Thanks, it should be fixed now.

**Comment by simonspa** [comment]
Looks fine to me now, but it's up to @ursl to merge it.

**Comment by ursl** [comment]
Hi Pirmin, 

I understand the purpose of you PR, but can you please explain the use case? Is it for running without ElComandante? Is it for running with scripts?

Cheers,
--U.

**Comment by piberger** [comment]
Hi Urs,

it is for running with scripts like

    cat testfile | pXar ...

which is also the way elComandante is doing it.
It was observed that if eg. the testfile contains

    Xray
    Xray
    Xray
    ...

with 30s measuring time for each, the peak position in the first spectrum is significantly off and the leakage current is unstable which hints to temperature instabilities.

**Comment by ursl** [comment]
OK. I am surprised that elComandante does not open a pipe into pxar and steer it more directly. With such a setup, elComandante could check for a stabilized leakage current before running tests. 

Adding "delay" to pxar is not a problem, but I think it is not the best solution to the problem. 

For the record: pXar should not get the capability to wait for stabilized leakage currents.

**Comment by rslu** [comment]
Hi Urs,
The request came from groups that do test without using elcommandate, e.g. CERN site.
Rong-Shyang

**Comment by piberger** [comment]
Yes, probably it could also be done in that way and I will have at look at it . 
As not everyone is using elComandante, adding the delay to pXar seems to be a more universal solution.

Checking whether the leakage current is stable is a bit more involved because there is not only the temperature dependence but also an overall decrease of the leakage current vs time. Additionally we can only measure the total leakage current of all 4 modules and not individually.

**Pull request merged**
