### PR TITLE
Update Production from master

### PR DESCRIPTION
**Pull request by simonspa**
I guess this should be fine, then we're up to the same level again.

### CODE REVIEW

**Comment by ursl** [comment]
Hi Simon,

I will create a new tag on the production branch when I am ready with my
local tests (currently running) to test the trimming and the timing of it.

Cheers,
--U.

**Comment by simonspa** [comment]
Hi Urs,

while browsing a log from a recent full test done with FW4.4 I encountered one more thing that coul now be done in one step. Currently I see
```
[14:12:58.754]     INFO: ######################################################################
[14:12:58.754]     INFO: PixTestBBMap::doTest() Ntrig = 16, VcalS = 250 (high range)
[14:12:58.754]     INFO: ######################################################################
[14:12:58.759]     INFO: ---> dac: VthrComp name: calSMap ntrig: 16 dacrange: 0 .. 149 (30/16) hits flags = 2 (plus default)
[14:12:58.782]     INFO:   dacScan step  from 0 .. 29
[14:12:58.782]     INFO:   dacScan split into 1 runs with ntrig = 16
[14:12:58.782]     INFO:     run 1 of 1
[14:12:59.133]     INFO: Expecting 1996800 events.
[14:13:33.559]     INFO: 1770768 events read in total (33647ms).
[14:13:38.403]     INFO: 1996800 events read in total (38491ms).
[14:13:38.406]     INFO: Test took 39624ms.
[14:13:38.409]     INFO: Fetched DAQ statistics. Counters are being reset now.
[14:13:38.409]     INFO:   dacScan step  from 30 .. 59
[14:13:38.409]     INFO:   dacScan split into 1 runs with ntrig = 16
[14:13:38.410]     INFO:     run 1 of 1
[14:13:38.972]     INFO: Expecting 1996800 events.
```

I guess we can now safely request all DAC settings in one go, just as we do for the SCurve test.

**Comment by simonspa** [comment]
One more speedup catch:

In PixTestGainPedestal, we currently request all data separately for every VCal setting. This could be done automatically by just setting `fVcalStep` directly in the API call:

Replace all of
```
for (unsigned int i = 0; i < fLpoints.size(); ++i) {
 ...
}
```
with the call from here: https://github.com/psi46/pxar/blob/master/core/api/api.h#L435
```
try {
  lresult = fApi->getPulseheightVsDAC("vcal", fVcalStep, 10, 255, FLAGS, fParNtig);
}
catch(pxarException &e) {
  LOG(logCRITICAL) << "pXar execption: "<< e.what();
}
```

This will automatically step through the VCal range with a step size of `fVcalStep` on NIOS level and return all data in one block.

**Comment by simonspa** [comment]
The same obviously applies for the high VCal range just below...

**Comment by ursl** [comment]
Hi Simon,

thanks.

The BB and BB3 mod was pushed.

For the gain/pedestal test the current code is not the original one.
It is not clear that it will stay in its current form. (It seems that
even the current "fine-grained" low-VCAL scan is not removing the
spikes in the low charge range completely. But maybe I am wrong here.)
The original setup, still present in the high range and formerly also
in the low range, was not relying on equidistant separation between
the points. Hence the loop.

This is off-topic: it is not clear to me that the "best" calibrations
should be done in the fulltest. It may be better to do them in the
(preparation for the) xray tests, since [at least at ETH] the time
spent in the xray setup is much less compared to the coldbox
qualification. That could considerably speed up the fulltest. I.e. one
could run the trim test with ntrig = 5-10 or so and the gain/pedestal
test with the old settings. Only for the xray setup one would rerun
those tests with the required precision. The down-side of this is that
the -20 calibration would suffer somewhat. However, there is no reason
why ntrig must be the same for both temperature ranges.

Cheers,
--U.

**Pull request merged**
