### PR TITLE
Introducing "PixTestDacDacScanMultipix"

### PR DESCRIPTION
**Pull request by dehuazhu**
This new usertest performs DacDacScans with 832 sample pixels of a roc,
scanning through all columns and 16 rows per column. This ensures that
all double columns are considered. This test is useful to illustrate
the summed DacDacscan of almost all pixels for various investigations.

### CODE REVIEW

**Comment by ursl** [comment]
Hi David,

can you please prepare a minimal PR, without the *.dat files? Your
modifications to testParameters.dat should go into mkConfig (preferably
into the part after "moreTestParameters.dat"; if you have problems with
perl simply send me by email a fragment of your parameters and I'll add
it). Static *.dat files should not be in the repository any more.

Many thanks.

Cheers,
--U.

**Comment by simonspa** [comment]
Hi,

to me it looks like this test currently runs in a very inefficient way since for every single one of the pixels the actual test is called:

```
for (unsigned int i = 0; i < fPIX.size(); ++i) {
    fApi->_dut->testPixel(fPIX[i].first, fPIX[i].second, true);
    fApi->_dut->maskPixel(fPIX[i].first, fPIX[i].second, false);
[...]
         rresults = fApi->getEfficiencyVsDACDAC(fParDAC1, fParLoDAC1, fParHiDAC1, 
					   fParDAC2, fParLoDAC2, fParHiDAC2, FLAGS, fParNtrig);
[...]
}
```

This causes lots of overhead, starting and stopping the DAQ etc. pxarCore has its own internal functions to split the test in the most efficient way available. Thus it would be much simpler (also code-wise) to just enable all pixels that you want and then call the test once:

```
for (unsigned int i = 0; i < fPIX.size(); ++i) {
    fApi->_dut->testPixel(fPIX[i].first, fPIX[i].second, true);
    fApi->_dut->maskPixel(fPIX[i].first, fPIX[i].second, false);
}

rresults = fApi->getEfficiencyVsDACDAC(fParDAC1, fParLoDAC1, fParHiDAC1, 
			   fParDAC2, fParLoDAC2, fParHiDAC2, FLAGS, fParNtrig);
```

This will deliver one big data structure with all pixel information in. And just for the sake of the argument: you could also compare the runtime of this agains running a DacDac test on a full ROC, because that will completely run on the DTB NIOS without PC involvement (just for data retrieval):

```
fApi->_dut->testAllPixels(true);
fApi->_dut->maskAllPixels(false);
rresults = fApi->getEfficiencyVsDACDAC(fParDAC1, fParLoDAC1, fParHiDAC1, 
			   fParDAC2, fParLoDAC2, fParHiDAC2, FLAGS, fParNtrig);
```

Cheers,
Simon

**Comment by ursl** [comment]
Hi Simon,

I have not yet looked at the code. But it is in "usertests", so by
definition all is permissible provided it compiles. Of course, also code in
usertests should be as fast as possible.

Cheers,
--U.

​

**Comment by simonspa** [comment]
I still don't get what this test is supposed to do, but as user test we can merge it anyway.

**Pull request merged**
