### PR TITLE
Changes in PhOpt Test considering suggestions from DESY.

### PR DESCRIPTION
**Pull request by dehuazhu**

### CODE REVIEW

**Comment by simonspa** [comment]
Does not even compile. Header file not committed probably.
https://travis-ci.org/psi46/pxar/jobs/83320545#L465

**Comment by ursl** [comment]
No, my first guess would be that the migration of the declaration
(definition?) of badpix into a for loop implies that it goes out of scope
after the for loop.

But the conclusion is clear: very bad.

Though shalt not commit/push untested code.

Cheers,
--U.

**Comment by simonspa** [comment]
Uh, @ursl obviously you are right, I didn't even read that far... :)

**Comment by simonspa** [comment]
new PR #411

**Pull request closed without merging**
