### PR TITLE
Add additional info to logfile lines and switching between histograms

### PR DESCRIPTION
**Pull request by piberger**
- add arbitrary info to logfile lines with option -L, eg. -L TB1 =>  [12:34:56.789] <TB1>   INFO: ... . This is useful for supervisor programs like elComandante that display all pxar log output from different TBs in one window
- add buttons "Previous V", "Next V" to switch between histograms of two different runs: *_V0 <-> *_V1 <-> *_V2 ... to easily compare changes for specific ROC/histogram
- stricter hot pixel criterion (for better Vcal spectrum)

### CODE REVIEW

**Comment by simonspa** [comment]
Core changes (log.h) look ok to me, fine for merging.
Ignore build error, just one repository server was unreachable during installation of build dependencies.

**Comment by simonspa** [comment]
Restarted the build, should be fine soonish.

**Comment by piberger** [comment]
How can you restart the Travis build?

**Comment by simonspa** [comment]
Click on the "restart the build" button on the TravisCI build page. :)
Not sure everyone can do it or only administrators if the repository...

**Comment by piberger** [comment]
Maybe only administrators can do it, I wanted to restart the build after I have seen the error where Travis could not connect to a server, but did not find an option for it on the build page.

**Comment by ursl** [comment]
Hi Pirmin, 

I pulled your PR. Could you please implement also the "wrap-around" like for the other "next/previous" buttons, i.e. that one can cycle through all Vx histograms staying on the same button? 

Many thanks. 

Cheers,
--U.

**Pull request merged**
