### PR TITLE
FPIX Changes

### PR DESCRIPTION
**Pull request by drberry85**
Urs and Simon,

I made some changes to the default timing generated by mkconfig and also eliminated the special setting for TBM08BFPIX as it was not and is no longer needed. I change the setTimings test to work with better for TBM08C, but for now we'll rely on findTiming() for TBM08C for the FPIX tests. I changed the default timings for FPIX but they won't be used in normal testing. TBM08A and TBM08B will use setTimings, as the new one is incompatible with those TBM types.

Doug

### CODE REVIEW

**Comment by ursl** [comment]
Hi Doug, 

can you please comment on 
(1) why the changes to PixTestPretest::checkreadbackbits(...) are good/necessary?
(2) why the same(?) function is replicated in PixTestTiming
(3) what happens if "ignorereadback" and "clocksdascan" are not present in testParameters.dat?

Many thanks.

Cheers,
--U.

**Comment by drberry85** [comment]
Urs,

 (1) why the changes to PixTestPretest::checkreadbackbits(...) are good/necessary?
The check readback bits in the pretest (and timing test) are only verifying that the timings are correct. What can happen is if the TBM phases and ROC delays are close but not 100% correct, you can have a properly formatted event but bit flips to in the last two bits in the ROC header (0111111110XX). If this happens, it's an indication that the timings are bad. I do the readback bit check before the decoding check because if it fails much quicker than the decoding test.

(2) As I said in (1) it's needed for timing. I could add it to PixTest.cc if you don't want it duplicated in two different tests.

(3) I assume you mean fNoTokenPass and fIgnoreReadBack. They are uninitialized in PixTestTiming.hh, so they will be randomly assigned to a 0 or 1 because they are bools. I can change PixTestTiming::PixTestTiming() such that they'll always be 0 if the check boxes are missing in mkconfig.

Doug

**Comment by ursl** [comment]
Hi Doug, 

thanks. If the same function is used in two places, then please put into PixTest. We should avoid code duplication. And please initialize the new parameters (to avoid other users being hit for being lazy and not re-creating their testParameters.dat file). 

Cheers,
--U.

**Comment by drberry85** [comment]
Sure Urs,
I'll make the changes and test them this afternoon.
Doug

**Pull request merged**
