### PR TITLE
DTB Firmware 4.0 & new features

### PR DESCRIPTION
**Pull request by simonspa**
This adds support for the latest DTB firmware 4.0:

 * selection of all available trigger sources (via pxarCore::daqTriggerSource())
 * automattic ROC Reset when WBC is changed (also at startup). This should make all single ROC reset user code obsolete
 * Send single signals to the chip without reprogramming the PG (via pxarCore::daqTriggerSingleSignal())
 * Detection and decoding of data from SoftTBM ( TBM emulator)
...and some more features.

This software ran successfully one week in the DESY testbeam recoding data from several million external triggers from the beam telescope setup.

Please make sure that also all tests work as they should.

### CODE REVIEW

**Comment by simonspa** [comment]
It would be nice to get feedback at the meeting tomorrow.

**Comment by ursl** [comment]
Hi Simon, 

I have problems with your branch and FW4.0. It compiles fine, despite the Travis complaint. 

My normal mode of setting up my module seems successful (i.e. I can run repeated VthrComp-CalDel scans with large ntrig without observing r/o errors). 

I then start a fulltest, but sooner or later (normally during the scurves) I get 

[09:20:46.154]     INFO: ---> dac: VthrComp name: scurveVthrComp ntrig: 20 dacrange: 0 .. 119 hits flags = 16 (plus default)
[09:20:46.168]     INFO:   dacScan step  from 0 .. 39
[09:21:29.399]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (2) != Token Chain Length (8)
[09:21:29.399]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (70) !=  TBM ID (117)
[09:21:29.399]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (118) !=  TBM ID (249)
[09:21:29.399]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (3) != Token Chain Length (8)
[09:21:29.399]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (250) !=  TBM ID (71)
[09:21:29.399]  WARNING: ROC 0: Readback start marker after 17 readouts!
[09:21:29.399]  WARNING: ROC 1: Readback start marker after 17 readouts!
[09:21:29.399]  WARNING: ROC 3: Readback start marker after 15 readouts!
[09:21:29.399]  WARNING: ROC 4: Readback start marker after 15 readouts!
[09:21:29.399]  WARNING: ROC 5: Readback start marker after 15 readouts!
[09:21:29.399]  WARNING: ROC 6: Readback start marker after 15 readouts!
[09:21:29.399]  WARNING: ROC 7: Readback start marker after 15 readouts!
[09:21:35.886] CRITICAL: <hal.cc/MultiRocAllPixelsDacScan:L971> Incomplete DAQ data readout! Missing -1 Events.
[09:22:19.288]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (2) != Token Chain Length (8)
[09:22:19.288]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (70) !=  TBM ID (117)
[09:22:19.288]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (118) !=  TBM ID (249)
[09:22:19.288]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (3) != Token Chain Length (8)
[09:22:19.288]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (250) !=  TBM ID (71)
[09:22:19.288]  WARNING: ROC 0: Readback start marker after 17 readouts!
[09:22:19.288]  WARNING: ROC 1: Readback start marker after 17 readouts!
[09:22:19.288]  WARNING: ROC 3: Readback start marker after 15 readouts!
[09:22:19.288]  WARNING: ROC 4: Readback start marker after 15 readouts!
[09:22:19.288]  WARNING: ROC 5: Readback start marker after 15 readouts!
[09:22:19.288]  WARNING: ROC 6: Readback start marker after 15 readouts!
[09:22:19.288]  WARNING: ROC 7: Readback start marker after 15 readouts!
[09:22:25.760] CRITICAL: <hal.cc/MultiRocAllPixelsDacScan:L971> Incomplete DAQ data readout! Missing -1 Events.
[09:23:09.165]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (2) != Token Chain Length (8)
[09:23:09.165]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (70) !=  TBM ID (117)
[09:23:09.165]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (118) !=  TBM ID (249)
[09:23:09.165]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (3) != Token Chain Length (8)
[09:23:09.165]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (250) !=  TBM ID (71)
[09:23:09.165]  WARNING: ROC 0: Readback start marker after 17 readouts!
[09:23:09.165]  WARNING: ROC 1: Readback start marker after 17 readouts!
[09:23:09.165]  WARNING: ROC 3: Readback start marker after 15 readouts!
[09:23:09.165]  WARNING: ROC 4: Readback start marker after 15 readouts!
[09:23:09.165]  WARNING: ROC 5: Readback start marker after 15 readouts!
[09:23:09.165]  WARNING: ROC 6: Readback start marker after 15 readouts!
[09:23:09.165]  WARNING: ROC 7: Readback start marker after 15 readouts!
[09:23:15.818] CRITICAL: <hal.cc/MultiRocAllPixelsDacScan:L971> Incomplete DAQ data readout! Missing -1 Events.
[09:23:16.227]     INFO:   dacScan step  from 40 .. 79
[09:23:54.700]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (2) != Token Chain Length (8)
[09:23:54.700]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (60) !=  TBM ID (117)
[09:23:54.700]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (118) !=  TBM ID (60)
[09:23:54.700]  WARNING: ROC 0: Readback start marker after 17 readouts!
[09:23:54.700]  WARNING: ROC 1: Readback start marker after 17 readouts!
[09:24:12.282]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (4) != Token Chain Length (8)
[09:24:12.282]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (211) !=  TBM ID (117)
[09:24:12.282]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (118) !=  TBM ID (211)
[09:24:12.283]  WARNING: ROC 0: Readback start marker after 17 readouts!
[09:24:12.283]  WARNING: ROC 1: Readback start marker after 17 readouts!
[09:24:12.283]  WARNING: ROC 2: Readback start marker after 17 readouts!
[09:24:12.283]  WARNING: ROC 3: Readback start marker after 17 readouts!
[09:24:12.585] CRITICAL: <hal.cc/MultiRocAllPixelsDacScan:L971> Incomplete DAQ data readout! Missing -2 Events.
[09:24:51.123]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (5) != Token Chain Length (8)
[09:24:51.123]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (25) !=  TBM ID (117)
[09:24:51.123]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (118) !=  TBM ID (248)
[09:24:51.123]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (5) != Token Chain Length (8)
[09:24:51.123]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (249) !=  TBM ID (26)
[09:24:51.124]  WARNING: ROC 0: Readback start marker after 17 readouts!
[09:24:51.124]  WARNING: ROC 1: Readback start marker after 17 readouts!
[09:24:51.124]  WARNING: ROC 2: Readback start marker after 17 readouts!
[09:24:51.124]  WARNING: ROC 3: Readback start marker after 17 readouts!
[09:24:51.124]  WARNING: ROC 4: Readback start marker after 17 readouts!
[09:24:51.124]  WARNING: ROC 5: Readback start marker after 15 readouts!
[09:24:51.124]  WARNING: ROC 6: Readback start marker after 15 readouts!
[09:24:51.124]  WARNING: ROC 7: Readback start marker after 15 readouts!
[09:25:05.397]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (170) !=  TBM ID (117)
[09:25:05.398]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (118) !=  TBM ID (0)
[09:25:05.398]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (0) != Token Chain Length (8)
[09:25:05.398]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (1) !=  TBM ID (171)
[09:25:05.667] CRITICAL: <hal.cc/MultiRocAllPixelsDacScan:L971> Incomplete DAQ data readout! Missing -2 Events.
[09:25:44.939]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (104) !=  TBM ID (117)
[09:25:44.939]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (118) !=  TBM ID (0)
[09:25:44.939]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (0) != Token Chain Length (8)
[09:25:44.939]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (1) !=  TBM ID (105)
[09:26:02.686]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (1) != Token Chain Length (8)
[09:26:02.686]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (186) !=  TBM ID (117)
[09:26:02.686]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (118) !=  TBM ID (249)
[09:26:02.686]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (0) != Token Chain Length (8)
[09:26:02.686]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (250) !=  TBM ID (186)
[09:26:02.686]  WARNING: ROC 0: Readback start marker after 17 readouts!
[09:26:03.018] CRITICAL: <hal.cc/MultiRocAllPixelsDacScan:L971> Incomplete DAQ data readout! Missing -3 Events.
[09:26:03.736]     INFO:   dacScan step  from 80 .. 119
[09:26:50.633]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (5) != Token Chain Length (8)
[09:26:50.633]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (116) !=  TBM ID (17)
[09:26:50.633]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (10) != Token Chain Length (8)
[09:26:50.633]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (18) !=  TBM ID (117)
[09:26:50.633]  WARNING: ROC 5: Readback start marker after 15 readouts!
[09:26:50.633]  WARNING: ROC 6: Readback start marker after 15 readouts!
[09:26:50.633]  WARNING: ROC 7: Readback start marker after 15 readouts!
[09:27:11.674]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (4) != Token Chain Length (8)
[09:27:11.675]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (34) !=  TBM ID (17)
[09:27:11.675]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (18) !=  TBM ID (35)
[09:27:11.675]  WARNING: ROC 4: Readback start marker after 15 readouts!
[09:27:11.675]  WARNING: ROC 5: Readback start marker after 15 readouts!
[09:27:11.675]  WARNING: ROC 6: Readback start marker after 15 readouts!
[09:27:11.675]  WARNING: ROC 7: Readback start marker after 15 readouts!
[09:27:18.764]     INFO: Test took 75028ms.
// snip

With the old setup (FW3.6 and the HEAD master branch) I have not seen r/o errors with this module (TBM08B and digv2.0). 

I have also tried to run the timing test (potentially some timing might have changed with the new FW), but that simply led to a crash. I have not manually optimized the basee because the default settings seemed to pass my setup criteria so far (no r/o errors in the VthrComp-CalDel scan). 

I will try with different basee settings, but this will take more time. 

Cheers,
--U.

**Comment by ursl** [comment]
I think that with a manual phase optimization I cannot operate my TBM08B/digv2.0 module with this PR. 
If others have more luck, please post. It should be stressed that this module works out of the box with FW3.6 and the HEAD of the master branch (I verified this explicitely). 

I think this needs to be resolved by merging.

**Comment by simonspa** [comment]
I can't really explain this behavior. The code used for any tests is untouched with respect to the master branch for FW3.6.

Has this been reported to @meierb as the firmware developer?

Has anyone else tested this version with a module/DESER400? maybe @cfangmeier?

@ursl: could you post a log in DEBUGHAL level for me to cross-check a few things?

**Comment by frmeier** [comment]
@simonspa : I will be in the lab later today. If you want us to do any test(s), let us know. Would you be available for a chat on skype/vidyo/phone? Get in touch with me via private email.

**Comment by ursl** [comment]
I'll run with DEBUGHAL tomorrow (I had an appointment at 5, currently no longer at PSI).

**Comment by ursl** [comment]
And one additional point: When I say "cannot operate" I mean "cannot run a fulltest w/o readout errors" (and arbitrarily I consider "critical" r/o errors as fatal).

**Comment by simonspa** [comment]
@ursl indeed these errors should be treated as fatal.
@frmeier any testing of long-running calibration/readout/whatever is appreciated. I do not expect any problems with single ROCs/DESER160 since that was the one we were running on in test beam without problems. Mainly the DESER400 seems to have problems again. I will ping you via mail.

On a sidenote: the Travis build was failing because the root package we are fetching for installation was temporarily unavailable apparently, so nothing to do with the code.

**Comment by frmeier** [comment]
I ran a full test using module id N00604 (TBM08b, digv2, FPix). The module has some known issues with bump bonds. DTB was flashed with firmware 4.0. pXar was latest version from master plus this PR from Simon. Some example errors are given below, output with -dDEBUGHAL. After about half an hour I stopped this. The full log and the root file are available at /afs/cern.ch/user/f/frmeier/public/pxar_20150211_160820.{log,root}.

I have to mention that before I did that, I ran a pretest, a pixel alive and a BB-test in the gui and they looked fine. Ran that without extra debug information while in the gui.

```
[15:35:25.917]     INFO:    ----------------------------------------------------------------------
[15:35:25.917]     INFO:    PixTestAlive::addressDecodingTest() ntrig = 10, vcal = 200 (ctrlreg = 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
[15:35:25.917]     INFO:    ----------------------------------------------------------------------
[15:35:28.925]     INFO: Test took 3005ms.
[15:35:28.945]    ERROR: <api.cc/repackMapData:L1713> This pixel doesn't belong here: ROC 0 [31,79,10]. Expected [31,0,x]
[15:35:28.945]    ERROR: <api.cc/repackMapData:L1713> This pixel doesn't belong here: ROC 0 [31,79,8]. Expected [31,1,x]
[15:35:28.945]    ERROR: <api.cc/repackMapData:L1713> This pixel doesn't belong here: ROC 0 [31,79,8]. Expected [31,2,x]
[15:35:28.945]    ERROR: <api.cc/repackMapData:L1713> This pixel doesn't belong here: ROC 0 [31,79,8]. Expected [31,3,x]
[15:35:28.945]    ERROR: <api.cc/repackMapData:L1713> This pixel doesn't belong here: ROC 0 [31,79,6]. Expected [31,4,x]
[15:35:28.945]    ERROR: <api.cc/repackMapData:L1713> This pixel doesn't belong here: ROC 0 [31,79,10]. Expected [31,5,x]
[15:35:28.945]    ERROR: <api.cc/repackMapData:L1713> This pixel doesn't belong here: ROC 0 [31,79,6]. Expected [31,6,x]
```

```
[15:37:16.009]     INFO: ######################################################################
[15:37:16.009]     INFO: PixTestScurves::fullTest() ntrig = 20
[15:37:16.009]     INFO: ######################################################################
[15:37:16.010]     INFO: adjusting VCAL to have VthrComp average threshold at default VthrComp
[15:37:18.619]     INFO: Test took 2603ms.
[15:37:27.364]     INFO: Test took 8706ms.
[15:37:27.684]     INFO: ---> dac: VthrComp name: scurveVthrComp ntrig: 20 dacrange: 0 .. 119 hits flags = 16 (plus default)
[15:37:27.692]     INFO:   dacScan step  from 0 .. 39
[15:38:10.621]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (0) != Token Chain Length (8)
[15:38:10.621]    ERROR: <datapipe.cc/CheckEventID:L153>    Event ID mismatch:  local ID (185) !=  TBM ID (186)
[15:38:10.621]  WARNING: ROC 3: Readback start marker after 14 readouts!
[15:38:10.621]  WARNING: ROC 0: Readback start marker after 14 readouts!
[15:38:10.621]  WARNING: ROC 1: Readback start marker after 14 readouts!
[15:38:10.621]  WARNING: ROC 2: Readback start marker after 14 readouts!
[15:38:10.621]  WARNING: ROC 4: Readback start marker after 14 readouts!
[15:38:10.621]  WARNING: ROC 5: Readback start marker after 14 readouts!
[15:38:10.621]  WARNING: ROC 6: Readback start marker after 14 readouts!
[15:38:10.621]  WARNING: ROC 7: Readback start marker after 14 readouts!
[15:38:17.341]     INFO: Test took 49649ms.
[15:38:17.790]     INFO:   dacScan step  from 40 .. 79
```

**Comment by ursl** [comment]
Hi all,

just for completeness: -dDEBUGHAL will not give "DEBUGHAL" output. It
should be "-v DEBUGHAL". What you got is INFO, the default (to which it
falls back if no parseable verbosity level is provided).

I have put my version into
https://gist.github.com/ursl/d4f29e05659b713f6abc

or
https://gist.githubusercontent.com/ursl/d4f29e05659b713f6abc/raw/gistfile1.txt

I think a straightforward way to reproduce the problems is to use a module
and then:

./mkConfig -m -d testModule -t TBM08B -r digv2   # or whatever module type
you have
../bin/pXar -d testModule -t Scurves -p "dac=vthrcomp;dacs/step=40"

I'll talk to Beat in the coffee break (assuming he's here).

Cheers,
--U.

**Comment by simonspa** [comment]
@frmeier: As pointed out by @ursl the log is only with INFO level. However, there are still some conclusions I can draw from this:

To me it looks like the DESER400 has problems sampling the data. Most obviously (beside the wrongly decoded pixels) you can see this in the lines where

```
[15:36:27.843]    ERROR: <datapipe.cc/DecodeDeser400:L319> Number of ROCs (6) != Token Chain Length (8)
```

only 6 out of 8 ROC headers can be found in this particular event. This really points to bad data after sampling by the DESER400.

@ursl: by "timing test" you beam @drberry85's PixTestTiming? How did the SdaClk scan look like? I only expect the DTB delays to change, this should have nothing to do with the TBM's basee setting IMO.

**Comment by simonspa** [comment]
Any news on this?

**Comment by ursl** [comment]
Not really. With timing test I mean indeed Doug's test. I have not
investigated why it crashed. Maybe insufficient protection against corrupt
input.

I think the clk/sda settings are fine.

**Comment by frmeier** [comment]
If you also meant to ping me: I was busy with CRUZET alignment yesterday. If you like to repeat the test with proper debug out (sorry, my fault, hsould have known better but used a software with -dXXX lately and even missed the obvious other meanung of -d in pXar...) I can do it later today.

**Comment by frmeier** [comment]
Sorry, wrong button. Reopened it immediately.

**Comment by simonspa** [comment]
Did anyone test this with a module again? @urs did you talk to beat?

I think it's quite important to get this solved, otherwise the codebase starts to diverge and merging becomes messy.

Also finding the issue here could point us to a general flaw of our module readout.

**Comment by ursl** [comment]
Hi Simon, 

Beat is not aware of anything in the f/w changes that should affect the r/o. I have not made progress on this front in the past week. 

Cheers,
--U.

**Comment by ursl** [comment]
Hi Simon, 

have you tried to reproduce the problem yourself with the recipe I provided above? 

Cheers,
--U.

**Comment by simonspa** [comment]
After receiving detailed logs from @drberry85 I see that all the RPC calls that are made are still the same and the software behaves correctly. Since @meierb hasn't changed anything in Quartus here my conclusion is (once more) timing - phase shifts, delays,...

@drberry85's logs can be found here:
FW3.6: http://justpaste.it/jsc4
FW4.0: http://justpaste.it/jsc3

Do we send TBM Resets at some point? Currently I'm only automatically resetting the ROCs on WBC programming. This has not been done automatically in FW3.6 but required user intervention via PG-reprogramming and triggering.

**Comment by ursl** [comment]
marwees>cd pxar
marwees>grep -i resettbm */*.cc
tests/PixTest.cc:void PixTest::resetTBM() {
tests/PixTest.cc:  fPg_setup.push_back(make_pair("resettbm", 0)); //
PG_RESR b001000
tests/PixTest.cc:  LOG(logINFO) << "IGNORE THE WARNING ABOVE  (resetTBM sent)!";
tests/PixTestHighRate.cc:    if (string::npos !=
pgtmp[i].first.find("resettbm")) continue;
tests/PixTestHighRate.cc:    if (string::npos !=
pgtmp[i].first.find("resettbm")) continue;
tests/PixTestTiming.cc:  pg_setup.push_back(make_pair("resettbm", 25));
usertests/PixTestCmd.cc:                    if( t & 0x4000 ) { out <<
", ResetTBM";}
usertests/PixTestCmd.cc:    if (seq & 0x20 ) { pgsetup.push_back(
make_pair("resettbm", 10) ); delay+=11;}


There are no TBM resets sent at the moment.

**Comment by simonspa** [comment]
Do we need it? I don't have too much experience with modules...

**Comment by ursl** [comment]
To my knowledge and in my experience testing a handful of modules: no.

**Comment by simonspa** [comment]
Okay, then I'd say also this is out as potential source of errors.

**Comment by simonspa** [comment]
Closing, will be superseded by new PR soon.

**Pull request closed without merging**
