### PR TITLE
Extensive error reporting

### PR DESCRIPTION
**Pull request by simonspa**
This branch adds a new class to pxarCore: `pxar::statistics`

the class collects all decoding statistics gathered during one DAQ session (i.e. one test command from pxarCore or one session started with `daqStart()` and ended with `daqStop()`.

It is meant for one-time-reading which means after calling `pxarCore::getStatistics()` the object will be returned and the internal statistics reset. Calling `getStatistics()` a second time will yield an empty object. This implies that if you want to check different values of the struct you have to fetch it and store it locally before accessing class members such as `statistics::pixel_errors()` instead of calling `pxarCore::getStatistics().pixel_errors()`.

The members of the statistics class are not yet exhaustive, there might be more error conditions we add later on.

In addition to this purely informational collecting of information from data decoding there are also certain error conditions implemented that will immediately interrupt and abort the running data acquisition (i.e. the test). This might shorten the time until an (invalid) result is returned since we immediately abort after the first data has been returned from the DTB instead of running through the whole tests with invalid data.

Note that the statistics class object gets filled by the decoder pipeworks. This has an implication for poeple running their own DAQ sessions using `daqStart()` and `daqStop()`. If you fetch your data via `pxarCore::daqGetRawEvent()` the statistics object will remain empty because the data has not been passed through the decoder. If you run `pxarCore::daqGetEvent()` or `pxarCore::daqGetEventBuffer()` the statistics object will be properly filled. Events will continue to be added to these numbers until you either read them out (reading statistics resets the counters) or you re-started a new DAQ session (`daqStart()` initialises the counters to zero).

This has been tested using various modules (since most of the error conditions we read from the DESER400 status flags) and also some singe ROCs. However, some quirks might still lurk around, so please report them so I can work on fixing them.

### CODE REVIEW

**Comment by simonspa** [comment]
What I have not yet implemented are user switches to turn on/off some of the warnings and/or error checks that are implemented. Please request this on a per-error-basis if you need it.

**Comment by simonspa** [comment]
One more thing: in order to not change anything in the tests, all calls to `pxarCore::daqGetNDecoderErrors()` (which doesn't exist anymore) have been replaced with `pxarCore:getStatistics().pixel_errors()`. This subset of error tags represents what has been counted as decoder errors before. All tests calling this function should be reworked to make use of the full information from `pxarCore::getStatistics()` or at least to account for all types of errors we check for using `pxarCore::getStatistics().errors()`.

**Comment by simonspa** [comment]
@ursl, @werdmann you had any chance looking at this? I guess it should be merged rather sooner than later and should definitely go in before we release a module testing version.

**Comment by ursl** [comment]
Hi Simon,

I tried it. I get lots of error messages, e..g

[10:39:00.992]    ERROR: <datapipe.cc/CheckEventID:L127>    Event ID
mismatch:  local ID (144) !=  TBM ID (128)
[10:39:00.992]    ERROR: <datapipe.cc/CheckEventID:L127>    Event ID
mismatch:  local ID (144) !=  TBM ID (128)
[10:39:00.992]    ERROR: <datapipe.cc/CheckEventID:L127>    Event ID
mismatch:  local ID (144) !=  TBM ID (128)
[10:39:00.992]    ERROR: <datapipe.cc/CheckEventID:L127>    Event ID
mismatch:  local ID (144) !=  TBM ID (128)

I think given the unstable readout error situation the default printout
level should be note as verbose. Else we wait for printouts and disks
filling up.

Cheers,
--U.

**Comment by simonspa** [comment]
Hi

Does your pg contain a restbm signal?

Am 22. Januar 2015 10:41:09 MEZ, schrieb Urs Langenegger <notifications@github.com>:

**Comment by ursl** [comment]
I don't think so. I run a default DACDAC scan which pulls in the
default pg setup as defined in

https://github.com/psi46/pxar/blob/master/util/ConfigParameters.cc#L316

Cheers,
--U.

**Pull request merged**
