### PR TITLE
pxarCore 2.0

### PR DESCRIPTION
**Pull request by simonspa**
This PR updates the pxarCore library to version 2.0 adding several new functionalities, API functions, and bug fixes. A quick over view is given below.

pxarCore 2.0 requires DTB firmware 4.0 or later.

## Triggers:
  * Selection of all available trigger sources (via `pxarCore::daqTriggerSource()`)
  * New trigger sources are:
    * `async`/`extern`: asynchronous external trigger (DTB LEMO connector)
    * `sync`: synchronous external trigger: for daisy-chaining DTBs
    * `single`/`single_direct`: sending single ROC commands directly, bypassing the Pattern Generator. The `direct` version does not go via the TBM emulator
    * `generator`: sending triggers from internal generator
    * `pg`/`pg_direct`: good ol' Pattern Generator. The `direct` version is the one used up till now, sending pattern generator signals directly to the ROC, bypassing the TBM emulator.
    * `chain`/`sync_out`: trigger modes for chaining DTBs using synchronous triggering.
  * New DTB delays: external trigger delay (WBC compensation) and timeout (token return)
  * API extension: Send single signals to the chip without reprogramming the PG (via `pxarCore::daqTriggerSingleSignal()`)
  * API behaviour change: when no event is present, an exception is thrown insteasd of just returning an empty event (cmp. `pxar::DataNoEvent`)

## Analog ROCs:
  * Add support for programming, reading and decoding of analog PSI46v2 and PSI46v2_xdb chips
  * New DTB registers `tindelay` and `toutdelay` control the start and end point of the ADC sampling period as delays from the flying token signal.
  * New DTB register `adctimeout` sets the timeout in clock cycles after which the ADC sampling is stopped in case no token_out was sensed
  * Python CLI: add some simple scan function to plot address levels of analog chips
  * DAC RangeTemp (27) is now supported. If specified it will always be set as last DAC to enable temperature reading via LastDAC functionality (`pxarCore::daqGetReadback()`)

## Decoding:
  * Detection and decoding of data from SoftTBM (TBM emulator)
  * Detection of TBM emulator done automatically based on currently selected triggering mode
  * Reworked decoder modules to provide TBM type (`GetEnvelopeType()`) and ROC type (`GetDeviceType()`) in every step of the decoding chain.
  * Decoder module for analog ROCs with self-calibrating levels. Ultrablack and black levels are used to calculate all other address levels, UB and B are taken from the first ROC header and averaged over every new even arriving.
  * Allow decoding of several ROCs within one DESER160 or analog data stream (devices with simple token-chained ROCs, such as beam telescopes using PSI46 chips)

## Other improvements:
  * Reset ROC: automatic ROC Reset when WBC is changed (also at startup). This should make all single ROC reset user code obsolete. This is implemented starting v2.0.1
  * Trigger dictionary featuring lookup for all above mentioned trigger signals
  * TBM emulator is new device type (TBM_EMU)
  * Simplification of HAL internal handling of TBM types, `hal::daqStart()` does not require it as argument anymore.
  * `pxar::pixel()` has new memberfunction `pixel::encode()` to return encoded data stream for the pixel. Can be used for debugging purposes or for fun when bored.
  * Python CLI: loading and running predefined scripts now using `cmdline.sh -r <script>` or, in the CLI: `> run <script>`
  * Add experimental support for ROOT 6. Requires compiler with C++11.

## Known issues
People have been reporting problems of module readout (DESER400) using firmware 4.0 (see also #293 for reference). I have not tested this myself, investigation is still ongoing and hopefully resoled in a few days.

### CODE REVIEW

**Comment by simonspa** [comment]
One more important thing to mention for this PR i the changed behavior of DAQ functins when requesting data. It turned out not to be sufficient to return empty events in case none were recoded - this would lead to problems immediately e.g. in test beam when running with external triggers.

Thus all functions returning DAQ events now throw a `pxar::DataNoEvent` exception in case no event has been recorded. This means, in order not to crash the plane when there is no event, you have to alter your code to catch them:

```
try {
  pxar::rawEvent daqRawEvent = m_api->daqGetRawEvent();
  pxar::Event daqEvent = m_api->daqGetEvent();
  std::vector<pxar::rawEvent> daqRawEvents = m_api->daqGetRawEventBuffer();
  std::vector<pxar::Event> daqEvents = m_api->daqGetEventBuffer();
  std::vector<uint16_t> buffer = m_api->daqGetBuffer();
}
catch(pxar::DataNoEvent &) {
  // No event available in derandomize buffers (DTB RAM).
}
```

This change has been introduced in 78679ab583c84f2105b8fa40395ee564dbf626a5 and I will properly document this behavior in `api.h` - I just realized there is no mentioning of this in the function descriptors yet...

**Comment by simonspa** [comment]
All calls in tests and user tests should now be guarded by catching `pxar::DataNoEvent` exceptions.

**Comment by simonspa** [comment]
With the latest commits pxarCore is now able to decode data from multiple ROCs on a single DESER160 line.

**Comment by drberry85** [comment]
Simon and Urs,

After implementing the fix from Simon, I have done the phase scan in both FW3.6 and FW4.0 and the results are fairly consistent between the two. I don't see any problem with merging this pull request.

Doug

**Comment by ursl** [comment]
Hi Doug,

have you run a fulltest to validate this?

Cheers,
--U.

**Comment by drberry85** [comment]
Urs,

I ran a slightly older version of Simon code and it ran through the full test. The only issue was a few sporadic timing issues. Basically it looks like the timing of the modules or DTB is unstable. I suspect that it's a firmware/hardware issue. But the issue is present in BOTH the FW3.6 and FW4.0, so it's not a argument against merging.

Doug

**Comment by simonspa** [comment]
@drberry85 just for the sake of the argument, could you run the very latest version? Nothing should change, but since I touched the decoders it'd be nice to have a confirmation that everything still runs...

**Comment by drberry85** [comment]
Hey Simon and Urs,
I ran the full test and it runs. It just has the usual timing issues. You can see the log at:
https://drberry.web.cern.ch/drberry/FirmwareTesting_4.0/FullTest_FW4.0.log

Doug

**Comment by simonspa** [comment]
Hm, looks like a few events still get scrambled. Especially in the cases where the number of ROCs is not correct it really looks like the raw data is not entirely stable. I guess most of the other warnings are just a result of this.

However, you say it's the same with FW3.6 - so this seems like something we should improve on in general...

**Comment by drberry85** [comment]
Simon,

Yes, this is definitely something that will need to be fixed. But it's not the software, it's either the DTB or FW (it may even be a grounding issue). But I highly suspect it's the DTB. We were using our favorite DTB yesterday for cross-calibration, and so for this test we used one that was fairly good. I can try running the same test this afternoon with the good one.

Doug

**Comment by ursl** [comment]
Hi Doug,

thanks. I think you have many (10) "critical" r/o errors. I agree that
nevertheless the module was run well through the FullTest. One
question: Why was the timing test not run as part of the pretest?

I'll run the same test (FullTest from HEAD with merged f/w 4.0) Monday
morning at PSI (I am currently at CERN).

Cheers,
--U.

**Comment by drberry85** [comment]
Urs,

I am using the fw4.0-daq-decoding branch from Simon's repository (git@github.com:simonspa/pxar), which does not have the timing test in the pretest. It should be know that the pretest timing test will not solve this issue because it is on the frequency of 1 out of 1000000 (and we test 500 triggers). We can change it such that after it finds good timings it does a more intense timing check, but I suspect that this won't solve the issue. I think we will have this problem regardless of whichever timings we use, because it's a DTB issue. But I will test more this afternoon to confirm.

Doug

**Comment by simonspa** [comment]
Hej Urs and Doug,

Please only use the linked branch "pxarCore-2.0". It contains all the latest changes from master (which I merged in regularly) as well as all new functions. The branch "fw-4.0-daq-decoding" is quite outdated by now.

/Simon

Am 27. März 2015 15:51:27 MEZ, schrieb Urs Langenegger <notifications@github.com>:

**Comment by drberry85** [comment]
Urs and Simon,

I have retested two modules with the pxarCore-2.0 branch from Simon's repository and both of them have the unstable data stream with both the 3.6 and 4.0 firmware. You can see the pxarCore-2.0 log at: https://drberry.web.cern.ch/drberry/FirmwareTesting_4.0/FullTest_FW4.0_pxarCore-2.0.log

For both modules make it through the full test with the 4.0 firmware.

Doug

**Comment by simonspa** [comment]
This should now be ready for a merge, I solved the merge conflict and updated to master. Just hit the "Merge pull request" button after Travis-CI compilation went through fine.

**Comment by ursl** [comment]
Thanks.

Cheers,
--U.

**Pull request merged**
