### PR TITLE
20161011 zhud (#1)

### PR DESCRIPTION
**Pull request by dehuazhu**
- Changes for a better performance for L1 Modules.
- Change FullTest Sequence
- Trim (excluding defective Pixels within the Test)

### CODE REVIEW

**Comment by schuetzepaul** [comment]
As Simon mentioned, the error was found, which lead to the abort of the PreTest.
I would therefore keep the exceptions, which are removed in this PR, since those errors are indeed critical.
Are there any other opinions on that case?

**Comment by dehuazhu** [comment]
Hi Paul and Simon, 
Thank you for the comments.
I do understand that these errors are sometimes critical and one should treat it properly. I have simply found out by experience that removing these lines lead to layer 1 modules tests with less pxar crashes.
The error log is still enabled, so the user can still see these errors and it is up to him to decide whether the test should be aborted or not. 
How do you think is the proper way of treating these problems? 
Best,
David

**Comment by schuetzepaul** [comment]
Hi David,
the thing is, that not probably not everyone has a look into the logfile after testing modules. Therefore it still makes sense to throw an exception, in my opinion.
I, personally, would like a test to abort if something is really going wrong. E.g. in this Pretest-case, the timing was just set wrong and thus the rest of the test was useless. This is then a test I don't want to finish anyway and throwing exceptions is appropriate then.
Furthermore, if the TBM cores are out of sync, that might not be that much of an issue for a testing procedure since one is sending the same pulses to the same pixels over and over in many cases. But going to real data, e.g. for test beam activities, to my understanding this is a no-go.

Don't get me wrong, I don't want to tell you how your tests should be run. I'm just concerned that we are missing errors which are indeed critical. Thus I would rather try to run it with the fix in the test procedure instead of removing the exceptions.

Did you see more errors besides of the Pretest issues?

Paul

**Comment by simonspa** [comment]
view it from a different perspective: us throwing the exceptions in case of corrupted events uncovered the errors in the timing test fro L1 modules.

Your consequence of this should probably not be the removal of the exceptions that saved your test. ;)

**Comment by piberger** [comment]
We should then just make sure to not have unhandled critical exceptions in the timing test where we scan many different timing settings (most of which are not good) and we better not have criticals which just come from some bad timings. Should we catch DataChannelMismatch exceptions then in the high level findtiming functions?
Or is it (now) impossible that bad timings lead to a DataChannelMismatch exception?

**Comment by simonspa** [comment]
Well, just read the docs:
```
 /** This exception class is used whenever multiple DAQ channels are active and
   *  there is a mismatch in event count across the channels (i.e. channel 0
   *  still returns one event but channel 1 is already drained)
   */
```
and then decide if this is something within the allowed scope of the detector or not. I would say since you are scanning timing phases and the DESER400 might get confused by this and miss an event or merge two of them, it is okay to catch the exception.

Similarly, just read the other definitions and decide on a case-by-case basis whether this is likely to happen and whether it poses a problem in the reference frame of your current test.

**Comment by dehuazhu** [comment]
Thank you for explaining. I'm still trying to understand the critical errors:

For example, here I have the log file of M1000 Fulltest:

[commander_Fulltest.txt](https://github.com/psi46/pxar/files/588893/commander_Fulltest.txt)

During the BB test, I get several (five) errors like

[18:36:58.707] <TB1>    ERROR: <hal.cc/daqAllEvents:L1697> Channels report mismatching event numbers: 220 220 129 220 220 220 220 220 

But nevertheless, the Fulltest finished. I simply observed that with the uncommented line: hal.cc/daqAllEvents:L1698: throw DataEventNumberMismatch("Channels report mismatching event numbers: " + listVector(current_Event.triggerCounts()));, pxar stops during BB test. 

How would you suggest to treat this kind of problem?

**Comment by simonspa** [comment]
Again, and as above, just read what the error describes, think of what it means for your test and then decide what to do e.g. in the BB test.

The error says: 

> the TBM headers told me different event IDs - even they should be exactly the same since the cores are supposed to be in sync. However, due to some weird situation they are not. It might be, that I just had a bit flip in the transmission - but if there are more such events, maybe one of the cores is misbehaving?

then think of possible solutions:

> I could catch the error but monitor the numer of such errors since I have all the tools available for that. I could simply call
```
int nerrors = fApi->getStatistics().errors_event();
```
and check if this happens too often and then abort the test.

Or you could say: 

> Well, I want this test to succeed anyway, so I'll just catch all of them and ignore the errors, whatever caused them.

**Comment by simonspa** [comment]
And to add:

> But nevertheless, the Fulltest finished.

Obviously, if we stop looking at the output data, every test finishes.

**Comment by piberger** [comment]
````
I would say since you are scanning timing phases and the DESER400 
might get confused by this and miss an event or merge two of them, 
it is okay to catch the exception.
````
That's what I mean, we should not be that strict about such errors when scanning the timings. Letting pXar crash (and thus corrupting the .root file containing also possible valid data) with unhandled exceptions in _this_ case is not a good solution either, at least for us when testing many modules with an automated procedure.

@schuetzepaul We also see errors using L1 modules trimmed to low thresholds, e.g. 40 Vcal, testing with all (or almost all) pixels unmasked. Among many other errors, we also have rarely instances of DataEventNumberMismatch or DataChannelMismatch. I guess you have a L1 module now, so if you want to reproduce it, just trim to something between 35 and 45 and run PhRun test from Xray tab (even without X-rays).

**Comment by simonspa** [comment]
Just to be clear: letting a program crash is *never* a good solution. And exceptions are not meant to crash the program, but to notify upper classes about events happening on lower levels. The solution to this is not removing the exceptions but to correctly handle them on the test level.

**Comment by dehuazhu** [comment]
Thank you very much for the constructive feedback. I agree to properly catch the criticals is the best solution softwarewise. For now, it seems that implementing this functionality requires quite some time and effort. So I will just close this pull request and come with another PR when the changes are implemented.

**Comment by simonspa** [comment]
If you run 
```
git revert dccf07e4e58384fa0282b31642442dcc7efa86a6
```
and push to this branch, the rest can be merged.

**Comment by schuetzepaul** [comment]
Hi Pirmin,
sorry for the late answer.
I tried to reproduce the errors you mentioned, but our first L1 module hat one buggy TBM core. Now that I have a "good" one, I'm able to reproduce this issue.

To my knowledge, the L1 modules are somewhat noisy and produce crosstalk. We've been testing the module in the test beam and did not manage to use trimmings lower than your values.
I see, that the errors are in some way painful, but it shows you, that the data is indeed corrupt.

It is beyond my knowledge whether this corrupt data will later on affect the DAQ system. If they don't, we can of course start ignoring these errors, but more interesting would be to find the reasons. So if you need to go to low ( < 45 vcal) trimmings, please handle the exceptions (remove or catch them) locally, until we know, whether they are indeed critical or not.

Paul

**Pull request closed without merging**
