### PR TITLE
Fixed issue in readback bit check when token bypass was enabled

### PR DESCRIPTION
**Pull request by drberry85**
Hey Simon and Urs,
I wasn't checking the right ROCs when the token bypass was enabled on the TBM. This fixes that.
Doug

### CODE REVIEW

**Comment by ursl** [comment]
Hi Doug, 

I failed to understand why you choose to modify the loop variable inside the loop (iroc--). I think an infinite loop is not a problem here because you also modify/shrink rocids, but I just wonder whether you could not achieve the same in a more straightforward way. 

Cheers,
--U.

**Comment by drberry85** [comment]
Urs,

The reason for the iroc-- in the loop is because I'm looping through the rocids and if the ROC number is for a TBM with the token bypass enabled I need to remove the ROC number from rocids. This shortens the length of rocids by 1 and I need to move the index back one value so the loop does skip an index. A more clear solution is to duplicate the rocids, but that is slower and uses more memory. I can roll back to uses a ROClist and the rocids, if you prefer.

Doug

**Comment by ursl** [comment]
Hi Doug,

unless I misunderstand something here, memory and speed should be no
issue at all here. I'd be very much in favor of not modifying the loop
variable inside the loop. Many thanks.

Cheers,
--U.

**Comment by drberry85** [comment]
Hey Urs,
I think this is ready to merge. Let me know if you think I should rebase it.
Doug

**Comment by ursl** [comment]
Hi Doug,

looks good. Please go ahead.

Cheers,
--U.

**Comment by drberry85** [comment]
Thanks Urs, it's merged.

**Pull request merged**
