### PR TITLE
Masked pixels during timing tests

### PR DESCRIPTION
**Pull request by drberry85**
I masked the pixels during the timing test because it was causing various problems where the dut was not being initialized correctly. All timing tests should work once pXar is started.

### CODE REVIEW

**Comment by simonspa** [comment]
What do you mean by three DUT not being initialized correctly? Is there something that should be fixed on my side?

**Comment by drberry85** [comment]
Simon,

If you need to fix something, I'm not sure what. All I know is that if I don't set ```fApi->_dut->testAllPixels(false); ```
then the timing test will always fail out of the box (without running setvana before hand). I suspect that when pXar starts the dut is in an odd state. But I am really not sure why disabling the pixels solves the issue. I don't think the deserializer should have a problem with pixel hits during the decoding test. I have no reason for adding this code, besides the fact that if I don't add it, the data doesn't decode correctly.

Doug

**Comment by simonspa** [comment]
Hm, the DUT should always be in a well-defined state, all the pixelConfigs are initialized when created, here:
https://github.com/psi46/pxar/blob/master/core/api/datatypes.h#L254
By default, all newly created `pixelConfig`s are disabled and masked as safe status, as you can see from the constructor above.

Somehow when starting pxar, all `pixelConfig` objects supplied to pxarCore have the enable bit active and the mask bit low, probably from here:
https://github.com/psi46/pxar/blob/master/util/ConfigParameters.cc#L386
If you start a DAQ with that, pxarCore will actually pick up the enabled pixels and set their calibrate bit to true, here:
https://github.com/psi46/pxar/blob/master/core/api/api.cc#L1174
That would mean, that by default you are trying to calibrate every pixel at once it seems - which leads to broken readout as known (too many pixels or noisy pixels).

However, the whole device was masked (I just injected a call to `fApi->_dut->info()` right before annd after your new calls to compare) and should not produce any hit at all...

Maybe this was another instalment of that interesting 'feature' of the chip we recently discovered and that I fixed here:
https://github.com/simonspa/pxar/commit/62b5c6ec1cdf95d8418aa5b71ae56d03ff0de593

**Comment by drberry85** [comment]
Simon,

It looks like this is what's happening. I can either mask all the pixels or set them to inactive and the timing test works great. However, if I do neither then I get output like this:
https://drberry.web.cern.ch/drberry/ForSimon/BrokenTimings.log

You can see the first time I run the timing test I get a bunch of garbage. I can even confirm this on the scope.
https://drberry.web.cern.ch/drberry/ForSimon/BeforeSetVana.png
But after the setVana test everything looks fine.
https://drberry.web.cern.ch/drberry/ForSimon/AfterSetVana.png
In both cases all the pixels are unmasked and active. What's really weird is that the Vana dac for each ROC has already been tuned. So the set Vana test shouldn't change the ROC behavior.

Doug

**Comment by simonspa** [comment]
No, in that case it's thankfully not simonspa@62b5c6e but really just overflowing all readout buffers that we have... :)

The reason for a working test after `PreTest::setVana()` is found quickly then:
https://github.com/psi46/pxar/blob/master/tests/PixTestPretest.cc#L227
disables all pixels and does not turn them on again after the test... :)

I definitely vote for changing the behaviour of ConfigParameter.cc since with the current code the detector is left in a "dangerous" state. We're not actually programming the detector with this at startup, but when starting a DAQ without re-checking the settings we have a behaviour as you describe...

**Pull request merged**
