### PR TITLE
Add RTD monitoring histogram

### PR DESCRIPTION
**Pull request by drberry85**
Hey Simon and Urs,

I added an RTD monitoring histogram that we would like for fpix. The results for BPIX should not change. This required me to pass the HDI type to PixMonitor, which means I had to modify the constructor. I added an API call to get the temperature (with two magic numbers), and I also added a printout of the initial and final currents and temperature. Let me know if any of these changes don't meet the design philosophy of pXar.

Doug

### CODE REVIEW

**Comment by ursl** [comment]
Hi Doug,

thanks. I'll look at this on Monday.

Cheers,
--U.

**Comment by simonspa** [comment]
I don't have strong feelings about this but I guess I would keep the formula for temperature calculation out of the pxarCore library. Am I guessing correctly that the constants in there depend on the RTD network used?

**Comment by drberry85** [comment]
Simon,

I could add the temperature constants to the config parameters.

Doug

**Comment by simonspa** [comment]
Hi Doug,

not sure that would be necessary, but moving it into the pxarCore library would be the contrary I guess. What was the reason for removing it from the PixMonitor?

/Simon

**Comment by drberry85** [comment]
Simon,

I actually added the API call before I knew exactly where I would need it... but I ended up calling it in PixGui, PixMonitor, PixMonitorFrame, and pXar Main. So I could relocate everything to PixMonitor.

Doug

**Comment by drberry85** [comment]
Hey Simon,

I moved the getTemp method to be completely within PixMonitor, and reverted the api back to the upstream master. It works with a dummy DTB, but I can test it on an actual module later tonight.

Doug

**Comment by drberry85** [comment]
Hey Simon and Urs,
I tested it on a module and it just needed one little change and now it's working.
Doug

**Comment by simonspa** [comment]
Hi Doug, Urs,

Fine for me to merge.

/Simon

Am 26. September 2015 13:23:37 GMT+08:00, schrieb Doug Berry <notifications@github.com>:

**Comment by ursl** [comment]
Hi Doug, 

I don't like your proposal because it has the potential to further clutter the c'tor of PixMonitor for future things. I rather propose that the PixMonitor c'tor is changed to be initialized with PixSetup and then "all" information is accessible in there. See the master head. 

Cheers,
--U.

**Comment by drberry85** [comment]
Urs,

That should be doable. Hopefully I'll update my branch this afternoon.

Doug

**Comment by drberry85** [comment]
Hey Urs,

I tested it on a module and the new version works using PixSetip. Let me know if you want me to rebase it to clean up the history.

Doug

**Comment by ursl** [comment]
Hi Doug,

I have no opinion regarding the history.

Cheers,
--U.

**Comment by drberry85** [comment]
Urs,

Then this branch is ready to merge... unless there are other comments.

Doug

**Pull request merged**
